name: safein
description: "SAFEIN - Ứng dụng kiểm tra an toàn thực phẩm và dị ứng"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.2
  image_picker: ^0.8.6
  speech_to_text: ^6.6.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  intl: ^0.19.0
  image: ^4.1.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - chuoi.webp
  - assets/logo.svg
